import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Data Science Road Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Data Science <a className={styles.highlight} href="https://nextjs.org">RoadMap!</a>
        </h1>

        <p className={styles.description}>
          Sebastian Navarro{' '}
          <code className={styles.code}>Portfolio</code>
        </p>

        <p className={styles.description}>
          Roadmap url:{' '}
          <a className={styles.highlight}> Roadmap 2021</a>
        </p>

        <div className={styles.grid}>
          <Link href="/math">
            <a className={styles.card}>
              <h2>📚 Estadisticas y Matematicas &rarr;</h2>
              {/* <p>Estadistica descriptiva e inferencial, Diseno Experimental, Probalidad, Algebra Lineal, Calculo simple y multivariable.</p> */}
            </a>
          </Link>

          <Link href="/ml">
            <a className={styles.card}>
              <h2>🤖 Machine Learning &rarr;</h2>
              <p></p>
            </a>
          </Link>

          <Link href="/programming">
            <a className={styles.card}>
              <h2>🐍 Programación &rarr;</h2>
              <p></p>
            </a>
          </Link>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>🧑‍💻 Ingeniero de Datos &rarr;</h2>
            <p></p>
          </a>

          
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>🕸️ Extraccion de Informacion y Wrangling  &rarr;</h2>
            <p>
              
            </p>
          </a>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>🧪 Analisis Exploratorio de Datos, Analisis de Negocios  &rarr;</h2>
            <p>
              
            </p>
          </a>
        </div>
      </main>

      
    </div>
  )
}

export default Home
